version: "3.8"

services:
  web:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres.qppddchwrozexigaqyhb:xKPLKNpq2FV1sEm7@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: new_bookit
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
